export const GAMES_DATA = [
  {
    id: 'mobile-legends',
    slug: 'mobile-legends',
    name: 'Mobile Legends: Bang Bang',
    publisher: 'Moonton',
    category: 'moba',
    currencyName: 'Diamonds',
    badge: 'POPULER',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=500&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&auto=format&fit=crop&q=80',
    description: 'Top up Diamond Mobile Legends termurah, proses otomatis 1-3 detik langsung masuk ke akun game.',
    inputFields: [
      {
        id: 'userId',
        label: 'User ID',
        placeholder: 'Contoh: 12345678',
        type: 'text',
        required: true,
        helperText: 'Masukkan 8-10 digit User ID game Anda',
      },
      {
        id: 'zoneId',
        label: 'Zone ID / Server ID',
        placeholder: 'Contoh: 2026',
        type: 'text',
        required: true,
        helperText: 'Masukkan 4-5 digit di dalam kurung ()',
      },
    ],
    idGuideImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    idGuideTip: 'User ID & Zone ID dapat ditemukan di menu profil game pojok kiri atas (contoh: 12345678 (2026)).',
    denominations: [
      { id: 'ml-3', name: '3 Diamonds', amount: 3, bonus: 0, price: 1400, isPopular: false },
      { id: 'ml-5', name: '5 Diamonds', amount: 5, bonus: 0, price: 1800, isPopular: false },
      { id: 'ml-12', name: '12 Diamonds', amount: 12, bonus: 0, price: 3900, isPopular: false },
      { id: 'ml-50', name: '50 (+3) Diamonds', amount: 53, bonus: 3, price: 15500, isPopular: false },
      { id: 'ml-86', name: '86 Diamonds', amount: 86, bonus: 0, price: 23200, isPopular: true, badge: 'Best Seller' },
      { id: 'ml-172', name: '172 Diamonds', amount: 172, bonus: 0, price: 46500, isPopular: true },
      { id: 'ml-257', name: '257 Diamonds', amount: 257, bonus: 0, price: 69800, isPopular: false },
      { id: 'ml-706', name: '706 (+60) Diamonds', amount: 766, bonus: 60, price: 186000, isPopular: true, badge: 'Promo' },
      { id: 'ml-2195', name: '2195 (+360) Diamonds', amount: 2555, bonus: 360, price: 580000, isPopular: false },
      { id: 'ml-pass', name: 'Weekly Diamond Pass', amount: 1, bonus: 0, price: 28500, isPopular: true, badge: 'Hemat 70%' },
    ],
  },
  {
    id: 'free-fire',
    slug: 'free-fire',
    name: 'Free Fire',
    publisher: 'Garena',
    category: 'battle-royale',
    currencyName: 'Diamonds',
    badge: 'HOT',
    thumbnail: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=500&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop&q=80',
    description: 'Top up Free Fire Diamond resmi dan bergaransi, anti minus, proses kilat 24 jam.',
    inputFields: [
      {
        id: 'userId',
        label: 'Player ID Free Fire',
        placeholder: 'Contoh: 182736452',
        type: 'text',
        required: true,
        helperText: 'Masukkan 8-10 digit Player ID Anda',
      },
    ],
    idGuideTip: 'Player ID Free Fire bisa dilihat di bagian profil akun di bawah nama karakter.',
    denominations: [
      { id: 'ff-5', name: '5 Diamonds', amount: 5, bonus: 0, price: 1000, isPopular: false },
      { id: 'ff-50', name: '50 Diamonds', amount: 50, bonus: 0, price: 7500, isPopular: false },
      { id: 'ff-70', name: '70 Diamonds', amount: 70, bonus: 0, price: 9900, isPopular: true },
      { id: 'ff-140', name: '140 Diamonds', amount: 140, bonus: 0, price: 19500, isPopular: true, badge: 'Terlaris' },
      { id: 'ff-355', name: '355 Diamonds', amount: 355, bonus: 0, price: 49000, isPopular: false },
      { id: 'ff-720', name: '720 Diamonds', amount: 720, bonus: 0, price: 98000, isPopular: true },
      { id: 'ff-1440', name: '1440 Diamonds', amount: 1440, bonus: 0, price: 195000, isPopular: false },
      { id: 'ff-member-w', name: 'Member Mingguan', amount: 1, bonus: 0, price: 32000, isPopular: true, badge: 'Spesial' },
      { id: 'ff-member-m', name: 'Member Bulanan', amount: 1, bonus: 0, price: 125000, isPopular: false },
    ],
  },
  {
    id: 'genshin-impact',
    slug: 'genshin-impact',
    name: 'Genshin Impact',
    publisher: 'HoYoverse / Cognosphere',
    category: 'rpg',
    currencyName: 'Genesis Crystals',
    badge: 'EVENT',
    thumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=500&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
    description: 'Top up Genesis Crystal & Blessing of the Welkin Moon Genshin Impact langsung via UID resmi HoYoverse.',
    inputFields: [
      {
        id: 'userId',
        label: 'UID Akun Genshin',
        placeholder: 'Contoh: 812345678',
        type: 'text',
        required: true,
        helperText: 'UID terdiri dari 9 angka di sudut kanan bawah layar',
      },
      {
        id: 'server',
        label: 'Pilih Server',
        placeholder: 'Pilih Server',
        type: 'select',
        options: [
          { value: 'os_asia', label: 'Asia' },
          { value: 'os_usa', label: 'America' },
          { value: 'os_euro', label: 'Europe' },
          { value: 'os_cht', label: 'TW, HK, MO' },
        ],
        required: true,
        helperText: 'Pilih server sesuai dengan akun Anda',
      },
    ],
    idGuideTip: 'UID dapat dilihat pada pojok kanan bawah saat berada di dalam game atau di menu Paimon.',
    denominations: [
      { id: 'gi-welkin', name: 'Blessing of the Welkin Moon', amount: 1, bonus: 0, price: 69000, isPopular: true, badge: 'Paling Dicari' },
      { id: 'gi-60', name: '60 Genesis Crystals', amount: 60, bonus: 0, price: 14500, isPopular: false },
      { id: 'gi-300', name: '300 (+30) Genesis Crystals', amount: 330, bonus: 30, price: 71000, isPopular: false },
      { id: 'gi-980', name: '980 (+110) Genesis Crystals', amount: 1090, bonus: 110, price: 215000, isPopular: true },
      { id: 'gi-1980', name: '1980 (+260) Genesis Crystals', amount: 2240, bonus: 260, price: 435000, isPopular: false },
      { id: 'gi-3280', name: '3280 (+600) Genesis Crystals', amount: 3880, bonus: 600, price: 715000, isPopular: false },
      { id: 'gi-6480', name: '6480 (+1600) Genesis Crystals', amount: 8080, bonus: 1600, price: 1425000, isPopular: true, badge: 'Bonus Terbesar' },
    ],
  },
  {
    id: 'valorant',
    slug: 'valorant',
    name: 'Valorant',
    publisher: 'Riot Games',
    category: 'fps',
    currencyName: 'Points (VP)',
    badge: 'PROMO',
    thumbnail: 'https://images.unsplash.com/photo-1542751110-97427bbecf20?w=500&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1534423861386-85a16f5d13fd?w=1200&auto=format&fit=crop&q=80',
    description: 'Beli Valorant Points (VP) murah dan aman. Dapatkan skin Phantom dan Vandal impianmu sekarang.',
    inputFields: [
      {
        id: 'userId',
        label: 'Riot ID (Username#Tagline)',
        placeholder: 'Contoh: TenZ#NA1 atau Jett#IND',
        type: 'text',
        required: true,
        helperText: 'Sertakan tanda pagar (#) dan tagline akun Riot Anda',
      },
    ],
    idGuideTip: 'Riot ID Anda tertulis di client Riot atau di menu pertemanan (Username#Tagline).',
    denominations: [
      { id: 'val-125', name: '125 Valorant Points', amount: 125, bonus: 0, price: 14500, isPopular: false },
      { id: 'val-420', name: '420 Valorant Points', amount: 420, bonus: 0, price: 47500, isPopular: false },
      { id: 'val-700', name: '700 Valorant Points', amount: 700, bonus: 0, price: 77000, isPopular: true },
      { id: 'val-1375', name: '1375 Valorant Points', amount: 1375, bonus: 0, price: 148000, isPopular: true, badge: 'Favorit' },
      { id: 'val-2400', name: '2400 Valorant Points', amount: 2400, bonus: 0, price: 250000, isPopular: false },
      { id: 'val-4000', name: '4000 Valorant Points', amount: 4000, bonus: 0, price: 410000, isPopular: true },
      { id: 'val-8150', name: '8150 Valorant Points', amount: 8150, bonus: 0, price: 815000, isPopular: false },
    ],
  },
  {
    id: 'pubg-mobile',
    slug: 'pubg-mobile',
    name: 'PUBG Mobile',
    publisher: 'Level Infinite / Tencent',
    category: 'battle-royale',
    currencyName: 'Unknown Cash (UC)',
    badge: 'POPULER',
    thumbnail: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=500&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop&q=80',
    description: 'Top up UC PUBG Mobile resmi Indonesia via ID karakter. Buka Royale Pass dengan harga termurah.',
    inputFields: [
      {
        id: 'userId',
        label: 'Character ID PUBG Mobile',
        placeholder: 'Contoh: 5123456789',
        type: 'text',
        required: true,
        helperText: 'Masukkan 9-11 digit ID karakter numerik Anda',
      },
    ],
    idGuideTip: 'Buka profil PUBG Mobile Anda, Character ID berupa angka berada di bawah avatar pemain.',
    denominations: [
      { id: 'pubg-60', name: '60 UC', amount: 60, bonus: 0, price: 14500, isPopular: false },
      { id: 'pubg-325', name: '325 UC', amount: 325, bonus: 0, price: 72000, isPopular: true, badge: 'Royale Pass' },
      { id: 'pubg-660', name: '660 UC', amount: 660, bonus: 0, price: 145000, isPopular: true },
      { id: 'pubg-1800', name: '1800 UC', amount: 1800, bonus: 0, price: 365000, isPopular: false },
      { id: 'pubg-3850', name: '3850 UC', amount: 3850, bonus: 0, price: 725000, isPopular: false },
    ],
  },
  {
    id: 'honkai-star-rail',
    slug: 'honkai-star-rail',
    name: 'Honkai: Star Rail',
    publisher: 'HoYoverse',
    category: 'rpg',
    currencyName: 'Oneiric Shard',
    badge: 'BARU',
    thumbnail: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=1200&auto=format&fit=crop&q=80',
    description: 'Top up Oneiric Shard & Express Supply Pass Honkai: Star Rail resmi langsung masuk kilat.',
    inputFields: [
      {
        id: 'userId',
        label: 'UID Akun Star Rail',
        placeholder: 'Contoh: 800123456',
        type: 'text',
        required: true,
        helperText: 'UID berupa 9 digit angka',
      },
      {
        id: 'server',
        label: 'Pilih Server',
        placeholder: 'Pilih Server',
        type: 'select',
        options: [
          { value: 'prod_official_asia', label: 'Asia' },
          { value: 'prod_official_usa', label: 'America' },
          { value: 'prod_official_euro', label: 'Europe' },
          { value: 'prod_official_cht', label: 'TW, HK, MO' },
        ],
        required: true,
        helperText: 'Pilih server sesuai dengan akun Anda',
      },
    ],
    idGuideTip: 'UID terletak di kiri bawah layar atau di menu ponsel karakter.',
    denominations: [
      { id: 'hsr-pass', name: 'Express Supply Pass', amount: 1, bonus: 0, price: 69000, isPopular: true, badge: 'Rekomendasi' },
      { id: 'hsr-60', name: '60 Oneiric Shards', amount: 60, bonus: 0, price: 14500, isPopular: false },
      { id: 'hsr-330', name: '300 (+30) Oneiric Shards', amount: 330, bonus: 30, price: 71000, isPopular: false },
      { id: 'hsr-1090', name: '980 (+110) Oneiric Shards', amount: 1090, bonus: 110, price: 215000, isPopular: true },
      { id: 'hsr-2240', name: '1980 (+260) Oneiric Shards', amount: 2240, bonus: 260, price: 435000, isPopular: false },
      { id: 'hsr-8080', name: '6480 (+1600) Oneiric Shards', amount: 8080, bonus: 1600, price: 1425000, isPopular: true },
    ],
  },
];
